### ISSUE TITLE
Negative loss during MoFA training and NumPy SVD convergence error

### ISSUE THREAD

**Issue by sumeromer** [unibas-gravis/Occlusion-Robust-MoFA#13]
I downloaded the CelebA-HQ dataset, extracted 2D FAN key points, and provided CSV files: all_landmarks, train_landmarks, and val_landmarks. (I used the first 28k images as training and kept the rest in the validation file).

As far as I understood, there are four terms in the loss in the autoencoder training step, as described in Section 3.2 of the paper: $L_{pixel}$, $L_{per}$, $L_{lm}$, and $L_reg$ and the total loss is as follows:
$$L_{total} = 0.5 \cdot L_{pixel} +  0.25 \cdot L_{per} +  0.0005 \cdot L_{lm} +  0.1 \cdot L_reg$$

The test sample is visually good (I added a test snapshot from the 165500th step); however, can you help me to figure out the following issues? Thanks!

1. From the very beginning of the training, $L_{pixel}$ gets negative values. Why?
2. Regularization term is also increasing during training.
3. After training 71 epochs (original configuration is for 100 epochs), NumPy gives SVD error related to ``` estimate_norm```in util/preprocess.py. It is just a 5-point similarity transform, but I could not understand why it happens after training many epochs.

```bash
2022-09-30 05:06:29 INFO     [TRAIN]  Epoch 071 	 Iteration 0213 	 Loss -0.653  98.166  -1.777  0.270  0.639
2022-09-30 05:06:30 INFO     [TRAIN]  Epoch 071 	 Iteration 0214 	 Loss -0.598  110.840  -1.688  0.291  0.646
2022-09-30 05:06:32 INFO     [TRAIN]  Epoch 071 	 Iteration 0215 	 Loss -0.558  80.996  -1.584  0.270  0.668
2022-09-30 05:06:33 INFO     [TRAIN]  Epoch 071 	 Iteration 0216 	 Loss -0.554  104.242  -1.601  0.264  0.674
2022-09-30 05:06:34 INFO     [TRAIN]  Epoch 071 	 Iteration 0217 	 Loss -0.514  71.737  -1.486  0.264  0.669
2022-09-30 05:06:36 INFO     [TRAIN]  Epoch 071 	 Iteration 0218 	 Loss -0.571  81.775  -1.618  0.270  0.682
2022-09-30 05:06:37 INFO     [TRAIN]  Epoch 071 	 Iteration 0219 	 Loss -0.583  84.287  -1.643  0.260  0.680
/home/omersumer/anaconda3/envs/focus/lib/python3.8/site-packages/numpy/linalg/linalg.py:2154: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)
Traceback (most recent call last):
  File "s01_MoFA_petraining.py", line 272, in <module>
    main(args)
  File "s01_MoFA_petraining.py", line 228, in main
    loss,losses_return_, raster_image, raster_mask, fg_mask = proc(images,landmarks,False)
  File "s01_MoFA_petraining.py", line 143, in proc
    pred_feat = net_recog(image=raster_image,pred_lm=lm68.transpose(1,2))
  File "/home/omersumer/anaconda3/envs/focus/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/omersumer/Desktop/workspace/projects/3d-face/external/Occlusion-Robust-MoFA/models/networks.py", line 36, in forward
    M = estimate_norm_torch(pred_lm, 224)
  File "/home/omersumer/Desktop/workspace/projects/3d-face/external/Occlusion-Robust-MoFA/util/preprocess.py", line 227, in estimate_norm_torch
    M.append(estimate_norm(lm_68p_[i], H))
  File "/home/omersumer/Desktop/workspace/projects/3d-face/external/Occlusion-Robust-MoFA/util/preprocess.py", line 216, in estimate_norm
    tform.estimate(lm, src)
  File "/home/omersumer/anaconda3/envs/focus/lib/python3.8/site-packages/skimage/transform/_geometric.py", line 1362, in estimate
    self.params = _umeyama(src, dst, estimate_scale=True)
  File "/home/omersumer/anaconda3/envs/focus/lib/python3.8/site-packages/skimage/transform/_geometric.py", line 137, in _umeyama
    U, S, V = np.linalg.svd(A)
  File "<__array_function__ internals>", line 180, in svd
  File "/home/omersumer/anaconda3/envs/focus/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 1657, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/home/omersumer/anaconda3/envs/focus/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 98, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
```
![losses](https://user-images.githubusercontent.com/67150616/193235659-069581d7-c407-4bf0-a381-a42f409fa483.png)
![test_image_165500](https://user-images.githubusercontent.com/67150616/193235727-3e4eb161-6cc9-4f42-b6b9-ba08750c0d8c.png)

**Comment by yug125lk** [comment]
Hi, did you solve it? I've got the same issue.

**Comment by Th1KJun** [comment]
I also have got the same issue.

**Comment by ChunLLee** [comment]
Hi, here are answers to your questions:
Q1 : It is normal to have negative value for L_pix.
Q2: Once optimization starts, the parameters of the face model deviate from 0, thus the regularization term increases.
Q3: This error is potentially caused by NaNs during computation. Please check the following to see workarounds or simply continue training from a previous checkpoint.
[`numpy/issues/1588`](https://github.com/numpy/numpy/issues/1588)
