### ISSUE TITLE
Possible Bug In  RecogNetWrapper?

### ISSUE THREAD

**Issue by dtoniolo** [unibas-gravis/Occlusion-Robust-MoFA#7]
Hi and congratulations for the great work. I was checking out the paper and the implementation and I came across a line of code that, to the best of my understanding, could be a bug.

The line in question is [` image=resized`](https://github.com/unibas-gravis/Occlusion-Robust-MoFA/blob/4b3e4de5d6316d8945ccb50fe5eaec03a5297ce2/models/networks.py#L39) in the [implementation of `RecogNetWrapper` ](https://github.com/unibas-gravis/Occlusion-Robust-MoFA/blob/4b3e4de5d6316d8945ccb50fe5eaec03a5297ce2/models/networks.py) (reported below for convenience).

# Discussion
To the best of my understanding, the input images for the FOCUS models have pixel values normalised in the [0, 1] range, while the pretrained ArchFace networks use pixel values in [-1, 1]. In order to make the two systems compatible, inside `RecogNetWrapper` the pixel values are transformed according to the simple rule y=2x-1. However, the subsequent line effectively undoes this transformation.

Should the `` image=resized`` instruction actually be removed or am I misunderstanding something?

```python
class RecogNetWrapper(nn.Module):
    def __init__(self, net_recog, pretrained_path=None, input_size=112):
        super(RecogNetWrapper, self).__init__()
        net = get_model(name=net_recog, fp16=False)
        if pretrained_path:
            state_dict = torch.load(pretrained_path, map_location='cpu')
            net.load_state_dict(state_dict)
            print("loading pretrained net_recog %s from %s" %(net_recog, pretrained_path))
        for param in net.parameters():
            param.requires_grad = False
        self.net = net
        self.preprocess = lambda x: 2 * x - 1
        self.input_size=input_size
        
    def forward(self, image,pred_lm,is_shallow=False):

        M = estimate_norm_torch(pred_lm, 224)
        resized=resize_n_crop(image, M, self.input_size)
        #util.show_tensor_images(resized,batch=12)
        image = self.preprocess(resized)
        image=resized  # ← this line
        feature = self.net(image,is_shallow)
        id_feature = F.normalize(feature, dim=-1, p=2)
        return id_feature
```

**Comment by ChunLLee** [comment]
Thank you for pointing out!

see here for the change:
https://github.com/unibas-gravis/Occlusion-Robust-MoFA/commit/9d1c92707efceb13fc0782f33ab4ebaaa707a418

**Comment by sumeromer** [comment]
This bug is resolved, but somehow I receive an error related to the number of inputs in RecogNetWrapper, two lines below it.
models/networks.py (Line 40)

```bash
Traceback (most recent call last):                                                                                                                                                                                
File "Step1_Pretrain_MoFA.py", line 235, in <module>                                                                                                                                                                             
l_loss_,_, raster_image, raster_mask, fg_mask = proc(images,landmarks,True)                                                                                                           
File "Step1_Pretrain_MoFA.py", line 173, in proc                                                                                                                                                                                               pred_feat = net_recog(image=raster_image,pred_lm=lm68.transpose(1,2))                                                                                                                                                                      
File "/home/omersumer/anaconda3/envs/OR-MoFA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                                                  
result = self.forward(*input, **kwargs)                                                                                                                                                                                                    
File "/mnt/d/projects/3d-face/external/Occlusion-Robust-MoFA/models/networks.py", line 41, in forward                                                                                                                                          
feature = self.net(image,is_shallow)                                                                                                                                                                                                       
File "/home/omersumer/anaconda3/envs/OR-MoFA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                                                  result = self.forward(*input, **kwargs)                                                                                                                                                                                                  
TypeError: forward() takes 2 positional arguments but 3 were given
```

```python
image = self.preprocess(resized)
feature = self.net(image,is_shallow) # <-- goes to this line in networks.py.
id_feature = F.normalize(feature, dim=-1, p=2)
return id_feature
```

I think the iResNet backbone should take only the input, not this "is_shallow" variable. After removing it (giving only image), Step1-MoFA started training.
